name: todo2
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slidable:
  supabase_flutter: ^0.3.1
  image_picker: 
  flutter_secure_storage: 
  connectivity_plus:
  shared_preferences:
  intl:
  cached_network_image: ^3.2.1
  simple_gesture_detector:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  flutter_native_splash:

flutter:

  uses-material-design: true

  assets:
    - assets/splash_screen/splash.png
    - assets/start_page/avatars/
    - assets/changed_password.png
    - assets/nav_bar_icons/
    - assets/work_list/
    - assets/grey_avatar.jpg




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

