name: todo2
description: A new Flutter project.

publish_to: 'none' 


version: 3.7.8+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: 
  connectivity_plus:
  intl:
  cached_network_image: 
  percent_indicator:
  flutter_slidable:
  file_picker:
  dio:
  flutter_svg:
  # animations
  flutter_spinkit: ^5.1.0
  shimmer:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_native_splash:

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Black.ttf


  assets:
    - assets/splash_screen/splash.png
    - assets/start_page/avatars/
    - assets/nav_bar_icons/
    - assets/work_list/tune.svg
    - assets/detailed_task/


   



