name: todo2
description: A new Flutter project.

publish_to: 'none' 


version: 3.7.2+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_secure_storage: 
  connectivity_plus:
  intl:
  cached_network_image: 
  simple_gesture_detector:
  percent_indicator:
  flutter_slidable:
  image_picker: 
  file_picker:
  dio:
  # animations
  flutter_spinkit: ^5.1.0
  shimmer:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_native_splash:

flutter:

  uses-material-design: true

  assets:
    - assets/splash_screen/splash.png
    - assets/start_page/avatars/
    - assets/changed_password.png
    - assets/nav_bar_icons/
    - assets/work_list/
    - assets/grey_avatar.jpg
    - assets/detailed_task/




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

