name: todo2
description: Trainee app.
publish_to: 'none' 
version: 3.8.9+1
environment:
  sdk: ">=2.18.0-0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: 
  internet_connection_checker:
  intl:
  cached_network_image: 
  percent_indicator:
  flutter_slidable:
  file_picker: ^5.2.0
  dio: 5.2.1
  easy_localization: ^3.0.1
  flutter_svg:
  flutter_dotenv:
  drift: 
  sqlite3_flutter_libs: 
  path_provider: ^2.0.0
  path: 
  grouped_list: ^5.1.2
  get_it:
  # For charles
  http_proxy:
  network_info_plus:
  permission_handler:
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_native_splash:
  drift_dev: 
  build_runner: 

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Black.ttf


  assets:
    - assets/images/splash_screen/
    - assets/images/start_page/avatars/
    - assets/images/nav_bar_icons/
    - assets/images/tasks_list/
    - assets/images/detailed_task/
    - assets/images/profile/
    - assets/localization/
    - .env


   


